name: Actions

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [10, 12]

    steps:
    - uses: actions/checkout@vl
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@vl
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test
      env:
        Actions: true
        
    - name: yarn build
      run: |
        yarn run build --if-present
        
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        
    - name : Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
